name: publish


on:
  release:
    types:
      - published

jobs:

  publish-package:
    if: github.event_name == 'release'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: setup-uv
        uses: astral-sh/setup-uv@v5

      - name: install-dependencies
        run: |
          uv pip install --system hatch
          uv pip install --system ".[tests]"
      - name: build-package
        run: uv run hatch build

      - name: publish-package
        run: uv run hatch publish --user __token__ --auth $PYPI_TOKEN
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
