name: tests

on:
  push:

jobs:
  run-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.12"

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup-uv
        uses: astral-sh/setup-uv@v5

      - name: install-dependencies
        run: |
          uv pip install --system ".[tests]"

      - name: run-tests
        env:
          UNRAVEL_API_KEY: ${{ secrets.UNRAVEL_API_KEY }}
        run: uv run pytest . -s --cov --durations 0

      - uses: codecov/codecov-action@v5
